### ISSUE TITLE
Extending web app fails (fails to find config.xml)

### ISSUE THREAD

**Issue by jerryaldrichiii** [TheLunaticScripter/sharepoint#3]
# Error Output
https://gist.github.com/jerryaldrichiii/68baa3da8ea7e96f6c6d0b72bf53fea7

# Notes

This exists:
```
C:\inetpub\wwwroot\wss\VirtualDirectories\9092\
``` 
but the following does not:
```
C:\inetpub\wwwroot\wss\VirtualDirectories\9092c9a2ef20-d236-4b30-bb49-926c968c142b\web.config
```

**Comment by TheLunaticScripter** [comment]
Jerry I think this issues cause there isn't a path option passed in for the extension. I add this in the PR and the implementation should be adding ```path 'c:/inetpub/wwwroot/wss/VirtualDirectory/9092'```
