### ISSUE TITLE
Distributed cache creation issue

### ISSUE THREAD

**Issue by kmotipalli** [TheLunaticScripter/sharepoint#6]
action :create_svc do
  case new_resource.name
  when 'DistributedCacheService'
    dsc_resource 'ServicePoolManagedAccount' do
      resource :SPManagedAccount
      property :Ensure, 'Present'
      #property :AccountName, new_resource.svc_pool_acct
      property :Account, ps_credential(new_resource.farm_acct, new_resource.farm_pswd)
      property :Account, ps_credential(new_resource.svc_pool_acct, new_resource.svc_pool_pswd)
      property :PsDscRunAsCredential, ps_credential(new_resource.setup_acct, new_resource.setup_pswd)
    end
    dsc_resource 'DistributedCacheService' do
      resource :SPDistributedCacheService
      property :Ensure, 'Present'
      property :Name, 'AppFabricCachingService'
      property :CacheSizeInMB, new_resource.dist_cache_sizemb
      property :ServiceAccount, new_resource.svc_pool_acct
      property :PsDscRunAsCredential, ps_credential(new_resource.setup_acct, new_resource.setup_pswd)
      property :CreateFirewallRules, new_resource.dist_cache_firewall_rule
      property :ServerProvisionOrder, new_resource.cache_provision_order if new_resource.cache_provision_order
    end

We have defined the "DistributedService" block in cookbook and we are getting error.

**Comment by TheLunaticScripter** [comment]
@kmotipalli Can you post how you are consuming this resource and what the error is that you are getting so I can attempt to replicate your issue.

**Comment by kmotipalli** [comment]
sp_app_svc 'DistributedCacheService' do
  action :create_svc
  svc_pool_acct node['wbg_sharepoint']['svc_pool_acct']
  svc_pool_pswd node['wbg_sharepoint']['svc_pool_pswd']
  setup_acct node['wbg_sharepoint']['setup_acct']
  setup_pswd node['wbg_sharepoint']['setup_pswd']
end

**Comment by TheLunaticScripter** [comment]
@kmotipalli thank your for posting the resource implementation but I need the error from the chef-client run in order to better understand your issue.

**Comment by kmotipalli** [comment]
The sharepoint App that you are trying to install, DistributedCacheService is currently not supported.

**Comment by TheLunaticScripter** [comment]
@kmotipalli that is the error inside the resource when you are trying to create an app that I currently dont' have a resource for. Can you provide as a text file the chef-client run, not just snippets. That will significantly help me troubleshoot your issue.

**Comment by TheLunaticScripter** [comment]
Closed due to other issue opened with correct error.
