### ISSUE TITLE
Distributed cache service App timeout

### ISSUE THREAD

**Issue by kmotipalli** [TheLunaticScripter/sharepoint#7]
* sp_app_svc[DistributedCacheService] action create_svc[2017-09-08T16:07:36-04:00] INFO: Processing sp_app_svc[Distrib
utedCacheService] action create_svc (wbg_sharepoint::default line 334)

    * dsc_resource[ServicePoolManagedAccount] action run[2017-09-08T16:07:36-04:00] INFO: Processing dsc_resource[Servic
ePoolManagedAccount] action run (C:/chef/cache/cookbooks/sharepoint/resources/apps_n_services.rb line 188)
 (up to date)
    * dsc_resource[DistributedCacheService] action run[2017-09-08T16:07:37-04:00] INFO: Processing dsc_resource[Distribu
tedCacheService] action run (C:/chef/cache/cookbooks/sharepoint/resources/apps_n_services.rb line 195)

      ================================================================================
      Error executing action `run` on resource 'dsc_resource[DistributedCacheService]'
      ================================================================================

      Mixlib::ShellOut::CommandTimeout
      --------------------------------
      command timed out:
      ---- Begin output of powershell.exe -executionpolicy bypass -noprofile -noninteractive -command "trap [Exception]
{write-error -exception ($_.Exception.Message);exit 1};Invoke-DscResource -Method set -Name SPDistributedCacheService -P
roperty @{Ensure='Present';Name='AppFabricCachingService';CacheSizeInMB=1024;ServiceAccount='wb\spm13dev';PsDscRunAsCred
ential=(New-Object System.Management.Automation.PSCredential('wb\spm13dev',('01000000d08c9ddf0115d1118c7a00c04fc297eb010
00000e4958c862f35e44e9aeda5473b69ad030400000002000000000003660000c000000010000000f8d72620d6cfd5e92fb645bf064fdd9e0000000
004800000a00000001000000086fff31e2abecfe8198cd3803fd26d9320000000911b2e74b3b92c6e4d361bdf028a61e4362e8d140be1e8106da8560
6f6573dc21400000006a9faff9d3127c1d23861c8a0cb406e1d535ce1' | ConvertTo-SecureString)));CreateFirewallRules=$false} -Modu
le SharePointDsc -Verbose   4> 'C:/Users/spm13dev/AppData/Local/Temp/verbose20170908-6024-nuxnyh' | convertto-json -comp
ress -depth 5 > C:/Users/spm13dev/AppData/Local/Temp/json20170908-6024-1onbhmd";if ( ! $? ) { exit 1 } ----
      STDOUT:
      STDERR:
      ---- End output of powershell.exe -executionpolicy bypass -noprofile -noninteractive -command "trap [Exception] {w
rite-error -exception ($_.Exception.Message);exit 1};Invoke-DscResource -Method set -Name SPDistributedCacheService -Pro
perty @{Ensure='Present';Name='AppFabricCachingService';CacheSizeInMB=1024;ServiceAccount='wb\spm13dev';PsDscRunAsCreden
tial=(New-Object System.Management.Automation.PSCredential('wb\spm13dev',('01000000d08c9ddf0115d1118c7a00c04fc297eb01000
000e4958c862f35e44e9aeda5473b69ad030400000002000000000003660000c000000010000000f8d72620d6cfd5e92fb645bf064fdd9e000000000
4800000a00000001000000086fff31e2abecfe8198cd3803fd26d9320000000911b2e74b3b92c6e4d361bdf028a61e4362e8d140be1e8106da85606f
6573dc21400000006a9faff9d3127c1d23861c8a0cb406e1d535ce1' | ConvertTo-SecureString)));CreateFirewallRules=$false} -Module
 SharePointDsc -Verbose   4> 'C:/Users/spm13dev/AppData/Local/Temp/verbose20170908-6024-nuxnyh' | convertto-json -compre
ss -depth 5 > C:/Users/spm13dev/AppData/Local/Temp/json20170908-6024-1onbhmd";if ( ! $? ) { exit 1 } ----

      ProcessId: 6140
      app_name: C:\Windows\System32\WindowsPowerShell\v1.0\/powershell.exe
      command_line: powershell.exe -executionpolicy bypass -noprofile -noninteractive -command "trap [Exception] {write-
error -exception ($_.Exception.Message);exit 1};Invoke-DscResource -Method set -Name SPDistributedCacheService -Property
 @{Ensure='Present';Name='AppFabricCachingService';CacheSizeInMB=1024;ServiceAccount='wb\spm13dev';PsDscRunAsCredential=
(New-Object System.Management.Automation.PSCredential('wb\spm13dev',('01000000d08c9ddf0115d1118c7a00c04fc297eb01000000e4
958c862f35e44e9aeda5473b69ad030400000002000000000003660000c000000010000000f8d72620d6cfd5e92fb645bf064fdd9e00000000048000
00a00000001000000086fff31e2abecfe8198cd3803fd26d9320000000911b2e74b3b92c6e4d361bdf028a61e4362e8d140be1e8106da85606f6573d
c21400000006a9faff9d3127c1d23861c8a0cb406e1d535ce1' | ConvertTo-SecureString)));CreateFirewallRules=$false} -Module Shar
ePointDsc -Verbose   4> 'C:/Users/spm13dev/AppData/Local/Temp/verbose20170908-6024-nuxnyh' | convertto-json -compress -d
epth 5 > C:/Users/spm13dev/AppData/Local/Temp/json20170908-6024-1onbhmd";if ( ! $? ) { exit 1 }
      timeout: 600

      Resource Declaration:
      ---------------------
      # In C:/chef/cache/cookbooks/sharepoint/resources/apps_n_services.rb

      195:     dsc_resource 'DistributedCacheService' do
      196:       resource :SPDistributedCacheService
      197:       property :Ensure, 'Present'
      198:       property :Name, 'AppFabricCachingService'
      199:       property :CacheSizeInMB, new_resource.dist_cache_sizemb
      200:       property :ServiceAccount, new_resource.svc_pool_acct
      201:       property :PsDscRunAsCredential, ps_credential(new_resource.setup_acct, new_resource.setup_pswd)
      202:       property :CreateFirewallRules, new_resource.dist_cache_firewall_rule
      203:       property :ServerProvisionOrder, new_resource.cache_provision_order if new_resource.cache_provision_orde
r
      204:     end
      205:   when 'BCSServiceInstance'

      Compiled Resource:
      ------------------
      # Declared in C:/chef/cache/cookbooks/sharepoint/resources/apps_n_services.rb:195:in `block in class_from_file'

      dsc_resource("DistributedCacheService") do
        action [:run]

**Comment by TheLunaticScripter** [comment]
@kmotipalli You are hitting the timeout with this resource please increase the timeout by pulling down the latest cookbook adding the dsc_timeout property to the implementation of this resource 1500 should be sufficient and re-run.

**Comment by TheLunaticScripter** [comment]
Issue closed to no response post addition of timeout for Caching service.
